### ISSUE TITLE
Build an Expense Tracker 💰

### ISSUE THREAD

**Issue by nunyvega** [ByteBiteChef/ByteBiteChef.github.io#4]
## Objective
Hello Max! Ready to dive into another exciting project? This time, let's create an Expense Tracker that allows users to input expenses, categorize them, and keep track of the total expenditure. 

An important note here is that you'll need to learn new concepts, like [events and event listeners](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events). You'll also need to investigate approaches to add functionality that you have not worked on yet, like filtering content on user request. 

### Preview
This is how your project should look once you're done:

https://github.com/ByteBiteChef/ByteBiteChef.github.io/assets/16329583/8efbc652-1921-4f75-9841-b5046beb763e

I centered all the text by adding:
```
<style>
	* {
		text-align: center;
	}
</style>
```
We'll improve the styling of your first three projects once we're done with this one. 

---

##### Step 1: Setup HTML Structure 🏗
- [ ] Create an HTML file to layout the basic structure.
- [ ] Include input fields for the expense description, amount, and category.
- [ ] Add a button to submit new expenses.
- [ ] Create a section to display the list of expenses and the total expenditure.

##### Step 2: Link a JavaScript File 🖇
- [ ] Create a JavaScript file.
- [ ] Link this file to your HTML.

##### Step 3: Capturing Expense Data 📥
- [ ] Setup event listeners to capture the data entered by the user.
- [ ] Ensure you capture the description, amount, and category of each expense.

##### Step 4: Displaying Expenses 📋
- [ ] Display each expense in a list or table.
- [ ] Ensure that each entry shows the description, amount, and category.

##### Step 5: Calculating Total Expenditure 🧮
- [ ] Keep a running total of all expenses entered.
- [ ] Display the total expenditure prominently so that it is easy to see.

##### Step 6: Category Filtering 🔍
- [ ] Allow expenses to be filtered by category.
- [ ] Users should be able to see expenses from only one category at a time if they wish.

##### Step 7: Testing and Debugging 🐞
- [ ] Test your expense tracker thoroughly to ensure all functionalities work correctly.
- [ ] Debug and fix any issues that might arise during testing.

#### Notes 📝
- Tackle each step one at a time, making sure each functionality works before proceeding to the next.
- Feel free to reach out if you encounter any challenges or need clarification on any of the steps.
- Learning and googling is part of this project, but focus on searching for specific solutions.
---

Max, your progress so far has been incredible, excited to see your Expense Tracker come to life! Best of luck, and happy coding! 🚀

**Comment by ByteBiteChef** [comment]
HI! Thanks for this new project! It seems challenging, but I'm looking forward to learning how to do it! 
kind regards.

**Comment by ByteBiteChef** [comment]
Hello, I completed steps 1 and 2 creating the HTML and JS file.
In the HTML I created the structure, the three required inputs, a button to add the expenses, and a UL to display all the expenses. 

<img width="1520" alt="Screenshot 2023-10-30 at 10 36 02" src="https://github.com/ByteBiteChef/ByteBiteChef.github.io/assets/144017722/081c08a3-e2f4-4657-b5c5-a9cde2993542">

The JS file is linked to the HTML, and I wrote the steps to start with my code.   

<img width="1158" alt="Screenshot 2023-10-30 at 10 37 10" src="https://github.com/ByteBiteChef/ByteBiteChef.github.io/assets/144017722/cd8f4716-99c5-4682-af87-0d76af2ed5d5">

Cheers!

**Comment by nunyvega** [comment]
Looks good! Good approach dividing the logic into smaller steps with pseudocode 💪

**Comment by ByteBiteChef** [comment]
Hi!
Step 3 is done using the '.value' method instead 'event listener' It's already committed and pushed. Tanks

**Comment by ByteBiteChef** [comment]
I completed steps four and five, now we can see the values of the inputs displayed on a list. Also, above the list is the total amount of expenses.

**Comment by nunyvega** [comment]
The total expenses is not working on the live site. Maybe you forgot to push?

**Comment by nunyvega** [comment]
Recap of today's talk:
```
step 0: add a class to each li element that you create programmatically.
step 1: create a select in the HTML with 3 options, each with a value attribute containing the class.
step 2: create an event listener that listens for changes in the select element.
step 3: create a function that does a querySelectorAll and selects the category
step 4: add style.display = "none" to all li elements with the class in the same function

**Comment by ByteBiteChef** [comment]
Hi! After a small pause to revisit some concepts of datatypes among others, I came back to this project while doing a DOM course.
I completed step six using a 'for each' loop.
Thanks!

**Comment by nunyvega** [comment]
Nice! once you're done with testing, we'll move to a new project to get some more experience with CSS 🎨

**Comment by ByteBiteChef** [comment]
Hello!
Thank you for this project, it was very entertaining and challenging at the same time.
Filtering by category in step 6, was definitely the most difficult. But there was a different level of challenge in every step for sure. 
To have a better understanding of this project, I did a course in parallel about DOM https://www.udacity.com/course/javascript-and-the-dom--ud117#. Also, Alvaro gave me 'data-type' exercises. Check it out here! https://github.com/nunyvega/js-tests

If you want to take a look at the Expense tracker I leave a link below. 
https://bytebitechef.github.io/Exp-Tracker.html

Thanks!
